name: Publish on Cargo
      

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Publish
      run: cargo publish --token ${{ secrets.CARGO_TOKEN }} --verbose --release --all-features
      
